themeLight.addEventListener('click', () => {
    themeDefault.classList.remove('header__button1--active')
    themeDefault.classList.add('header__button1--inactive')
    themeLight.classList.remove('header__button2--inactive')
    themeLight.classList.add('header__button2--active')
    themeDark.classList.remove('header__button3--active')
    themeDark.classList.add('header__button3--inactive')

    header.classList.remove('header--1', 'header--3')
    header.classList.add('header--3')
    headerButtons.classList.remove('header__buttons--1')
    headerButtons.classList.remove('header__buttons--3')
    headerButtons.classList.add('header__buttons--2')
    body.classList.remove('body--1', 'body--3')
    body.classList.add('body--2')
    screen.classList.remove('screen--1')
    screen.classList.remove('screen--3')
    screen.classList.add('screen--2')
    screenH.classList.remove('screen__h--1')
    screenH.classList.remove('screen__h--3')
    screenH.classList.add('screen__h--2')
    grid.classList.remove('grid--1')
    grid.classList.remove('grid--3')
    grid.classList.add('grid--2')
    equalButton.classList.remove('equal-button--1')
    equalButton.classList.remove('equal-button--3')
    equalButton.classList.add('equal-button--2')
    colorButton.forEach(button => button.classList.remove('color-button--1'))
    colorButton.forEach(button => button.classList.remove('color-button--3'))
    colorButton.forEach(button => button.add('color-button--2'))
    numpad.forEach(button => button.classList.remove('numpad--1'))
    numpad.forEach(button => button.classList.remove('numpad--3'))
    numpad.forEach(button => button.classList.add('numpad--2'))
});